/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Included_com_reacheng_simlock_provision_NvRamNative */

#ifndef _Included_com_reacheng_simlock_provision_NvRamNative
#define _Included_com_reacheng_simlock_provision_NvRamNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     _Included_com_reacheng_simlock_provision_NvRamNative
 * Method:    writeNv
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_reacheng_simlock_provision_NvRamNative_writeNv
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
